apiVersion: apps/v1
kind: Deployment
metadata:
  name: hc-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hc-service
  template:
    metadata:
      labels:
        app: hc-service
    spec:
      containers:
        - name: hc-service
          image: vegasahoo/hc-service:latest  # ✅ Your Docker Hub image
          ports:
            - containerPort: 8080
